{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 112,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>SerialNo</th>\n",
       "      <th>ExternalRefID</th>\n",
       "      <th>CallID</th>\n",
       "      <th>CTLDispatchCallID</th>\n",
       "      <th>CTLAggregationID</th>\n",
       "      <th>Number</th>\n",
       "      <th>EarlyStart</th>\n",
       "      <th>DueDate</th>\n",
       "      <th>Priority</th>\n",
       "      <th>Area</th>\n",
       "      <th>Region</th>\n",
       "      <th>District</th>\n",
       "      <th>Postcode</th>\n",
       "      <th>TaskType</th>\n",
       "      <th>Duration</th>\n",
       "      <th>NumberOfRequiredEngineers</th>\n",
       "      <th>AppointmentStart</th>\n",
       "      <th>AppointmentFinish</th>\n",
       "      <th>Latitude</th>\n",
       "      <th>Longitude</th>\n",
       "      <th>Street</th>\n",
       "      <th>City</th>\n",
       "      <th>State</th>\n",
       "      <th>CountryID</th>\n",
       "      <th>CTLDispatchReady</th>\n",
       "      <th>ES+duration</th>\n",
       "      <th>AS+duration</th>\n",
       "      <th>(AS+duration&gt;=DD</th>\n",
       "      <th>(ES+duration&gt;=DD</th>\n",
       "      <th>Duration (hh:mm:ss)</th>\n",
       "      <th>DD-ES</th>\n",
       "      <th>ES&gt;=DD</th>\n",
       "      <th>DD-AS</th>\n",
       "      <th>AS&gt;=DD</th>\n",
       "      <th>AF&gt;DD</th>\n",
       "      <th>Note</th>\n",
       "      <th>Unnamed: 36</th>\n",
       "      <th>Unnamed: 37</th>\n",
       "      <th>Unnamed: 38</th>\n",
       "      <th>Unnamed: 39</th>\n",
       "      <th>Unnamed: 40</th>\n",
       "      <th>Unnamed: 41</th>\n",
       "      <th>Unnamed: 42</th>\n",
       "      <th>Unnamed: 43</th>\n",
       "      <th>Unnamed: 44</th>\n",
       "      <th>Unnamed: 45</th>\n",
       "      <th>Unnamed: 46</th>\n",
       "      <th>Unnamed: 47</th>\n",
       "      <th>Unnamed: 48</th>\n",
       "      <th>Unnamed: 49</th>\n",
       "      <th>Unnamed: 50</th>\n",
       "      <th>Unnamed: 51</th>\n",
       "      <th>Unnamed: 52</th>\n",
       "      <th>Unnamed: 53</th>\n",
       "      <th>Unnamed: 54</th>\n",
       "      <th>Unnamed: 55</th>\n",
       "      <th>Unnamed: 56</th>\n",
       "      <th>Unnamed: 57</th>\n",
       "      <th>Unnamed: 58</th>\n",
       "      <th>Unnamed: 59</th>\n",
       "      <th>Unnamed: 60</th>\n",
       "      <th>Unnamed: 61</th>\n",
       "      <th>Unnamed: 62</th>\n",
       "      <th>Unnamed: 63</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>213116</td>\n",
       "      <td>213116</td>\n",
       "      <td>MRNV1099624001F00</td>\n",
       "      <td>M/JUNETEST01/171231</td>\n",
       "      <td>1</td>\n",
       "      <td>2017-10-30T08:00:00</td>\n",
       "      <td>2017-10-30T17:00:00</td>\n",
       "      <td>4</td>\n",
       "      <td>NV</td>\n",
       "      <td>Las Vegas</td>\n",
       "      <td>East 2 NV</td>\n",
       "      <td>891156549.0</td>\n",
       "      <td>HSADSL2SANRIN</td>\n",
       "      <td>4800</td>\n",
       "      <td>1</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>36196753</td>\n",
       "      <td>-115071860</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>UNITED STATES</td>\n",
       "      <td>False</td>\n",
       "      <td>10/30/2017 9:20</td>\n",
       "      <td>1:20:00 AM</td>\n",
       "      <td>OK</td>\n",
       "      <td>OK</td>\n",
       "      <td>1:20:00 AM</td>\n",
       "      <td>0/1/00 9:00</td>\n",
       "      <td>D</td>\n",
       "      <td>2017-10-30T17:00:00</td>\n",
       "      <td>D</td>\n",
       "      <td>D</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>253122</td>\n",
       "      <td>253122</td>\n",
       "      <td>MRNV4542934002A00</td>\n",
       "      <td>H/1445077137</td>\n",
       "      <td>1</td>\n",
       "      <td>2017-10-27T08:00:00</td>\n",
       "      <td>2017-10-27T17:00:00</td>\n",
       "      <td>4</td>\n",
       "      <td>NV</td>\n",
       "      <td>Las Vegas</td>\n",
       "      <td>North 2 NV</td>\n",
       "      <td>890311803.0</td>\n",
       "      <td>XXXXXXXXXXXIH</td>\n",
       "      <td>4260</td>\n",
       "      <td>1</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>36272531</td>\n",
       "      <td>-115161580</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>UNITED STATES</td>\n",
       "      <td>True</td>\n",
       "      <td>10/27/2017 9:11</td>\n",
       "      <td>1:11:00 AM</td>\n",
       "      <td>OK</td>\n",
       "      <td>OK</td>\n",
       "      <td>1:11:00 AM</td>\n",
       "      <td>0/1/00 9:00</td>\n",
       "      <td>D</td>\n",
       "      <td>2017-10-27T17:00:00</td>\n",
       "      <td>D</td>\n",
       "      <td>D</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>253130</td>\n",
       "      <td>253130</td>\n",
       "      <td>MRNV4542934001A00</td>\n",
       "      <td>R/1445077137</td>\n",
       "      <td>1</td>\n",
       "      <td>2017-10-27T08:00:00</td>\n",
       "      <td>2017-10-27T17:00:00</td>\n",
       "      <td>4</td>\n",
       "      <td>NV</td>\n",
       "      <td>Las Vegas</td>\n",
       "      <td>North 2 NV</td>\n",
       "      <td>890311803.0</td>\n",
       "      <td>HSBNDA2FANRIN</td>\n",
       "      <td>14400</td>\n",
       "      <td>1</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>36272531</td>\n",
       "      <td>-115161580</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>UNITED STATES</td>\n",
       "      <td>True</td>\n",
       "      <td>10/27/2017 12:00</td>\n",
       "      <td>4:00:00 AM</td>\n",
       "      <td>OK</td>\n",
       "      <td>OK</td>\n",
       "      <td>4:00:00 AM</td>\n",
       "      <td>0/1/00 9:00</td>\n",
       "      <td>D</td>\n",
       "      <td>2017-10-27T17:00:00</td>\n",
       "      <td>D</td>\n",
       "      <td>D</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>29319</td>\n",
       "      <td>29319</td>\n",
       "      <td>TINVC014723001PTD01</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1</td>\n",
       "      <td>2017-10-27T09:00:00</td>\n",
       "      <td>2017-10-27T18:00:00</td>\n",
       "      <td>4</td>\n",
       "      <td>NV</td>\n",
       "      <td>Las Vegas</td>\n",
       "      <td>North 2 NV</td>\n",
       "      <td>89030.0</td>\n",
       "      <td>DSOCFEPREMDESX</td>\n",
       "      <td>6000</td>\n",
       "      <td>1</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>36195789</td>\n",
       "      <td>-115118216</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>UNITED STATES</td>\n",
       "      <td>True</td>\n",
       "      <td>10/27/2017 10:40</td>\n",
       "      <td>1:40:00 AM</td>\n",
       "      <td>OK</td>\n",
       "      <td>OK</td>\n",
       "      <td>1:40:00 AM</td>\n",
       "      <td>0/1/00 9:00</td>\n",
       "      <td>D</td>\n",
       "      <td>2017-10-27T18:00:00</td>\n",
       "      <td>D</td>\n",
       "      <td>D</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>296995</td>\n",
       "      <td>296995</td>\n",
       "      <td>MRNV4306921001A00</td>\n",
       "      <td>R/1446647892</td>\n",
       "      <td>1</td>\n",
       "      <td>2017-10-29T07:00:00</td>\n",
       "      <td>2017-10-29T19:00:00</td>\n",
       "      <td>4</td>\n",
       "      <td>NV</td>\n",
       "      <td>Las Vegas</td>\n",
       "      <td>West West NV</td>\n",
       "      <td>891444443.0</td>\n",
       "      <td>XXXXXXXXXXXIH</td>\n",
       "      <td>4260</td>\n",
       "      <td>1</td>\n",
       "      <td>2017-10-29T13:00:00</td>\n",
       "      <td>2017-10-29T17:00:00</td>\n",
       "      <td>36165665</td>\n",
       "      <td>-115331120</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>UNITED STATES</td>\n",
       "      <td>True</td>\n",
       "      <td>10/29/2017 8:11</td>\n",
       "      <td>2:11:00 PM</td>\n",
       "      <td>OK</td>\n",
       "      <td>OK</td>\n",
       "      <td>1:11:00 AM</td>\n",
       "      <td>0/1/00 12:00</td>\n",
       "      <td>D</td>\n",
       "      <td>1900-01-00T06:00:00</td>\n",
       "      <td>D</td>\n",
       "      <td>D</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   SerialNo  ExternalRefID  CallID    CTLDispatchCallID     CTLAggregationID  \\\n",
       "0         1         213116  213116    MRNV1099624001F00  M/JUNETEST01/171231   \n",
       "1         2         253122  253122    MRNV4542934002A00         H/1445077137   \n",
       "2         3         253130  253130    MRNV4542934001A00         R/1445077137   \n",
       "3         4          29319   29319  TINVC014723001PTD01                  NaN   \n",
       "4         5         296995  296995    MRNV4306921001A00         R/1446647892   \n",
       "\n",
       "   Number           EarlyStart              DueDate  Priority Area     Region  \\\n",
       "0       1  2017-10-30T08:00:00  2017-10-30T17:00:00         4   NV  Las Vegas   \n",
       "1       1  2017-10-27T08:00:00  2017-10-27T17:00:00         4   NV  Las Vegas   \n",
       "2       1  2017-10-27T08:00:00  2017-10-27T17:00:00         4   NV  Las Vegas   \n",
       "3       1  2017-10-27T09:00:00  2017-10-27T18:00:00         4   NV  Las Vegas   \n",
       "4       1  2017-10-29T07:00:00  2017-10-29T19:00:00         4   NV  Las Vegas   \n",
       "\n",
       "       District     Postcode        TaskType  Duration  \\\n",
       "0     East 2 NV  891156549.0   HSADSL2SANRIN      4800   \n",
       "1    North 2 NV  890311803.0   XXXXXXXXXXXIH      4260   \n",
       "2    North 2 NV  890311803.0   HSBNDA2FANRIN     14400   \n",
       "3    North 2 NV      89030.0  DSOCFEPREMDESX      6000   \n",
       "4  West West NV  891444443.0   XXXXXXXXXXXIH      4260   \n",
       "\n",
       "   NumberOfRequiredEngineers     AppointmentStart    AppointmentFinish  \\\n",
       "0                          1                  NaN                  NaN   \n",
       "1                          1                  NaN                  NaN   \n",
       "2                          1                  NaN                  NaN   \n",
       "3                          1                  NaN                  NaN   \n",
       "4                          1  2017-10-29T13:00:00  2017-10-29T17:00:00   \n",
       "\n",
       "   Latitude  Longitude  Street  City  State      CountryID  CTLDispatchReady  \\\n",
       "0  36196753 -115071860     NaN   NaN    NaN  UNITED STATES             False   \n",
       "1  36272531 -115161580     NaN   NaN    NaN  UNITED STATES              True   \n",
       "2  36272531 -115161580     NaN   NaN    NaN  UNITED STATES              True   \n",
       "3  36195789 -115118216     NaN   NaN    NaN  UNITED STATES              True   \n",
       "4  36165665 -115331120     NaN   NaN    NaN  UNITED STATES              True   \n",
       "\n",
       "        ES+duration AS+duration (AS+duration>=DD (ES+duration>=DD  \\\n",
       "0   10/30/2017 9:20  1:20:00 AM               OK               OK   \n",
       "1   10/27/2017 9:11  1:11:00 AM               OK               OK   \n",
       "2  10/27/2017 12:00  4:00:00 AM               OK               OK   \n",
       "3  10/27/2017 10:40  1:40:00 AM               OK               OK   \n",
       "4   10/29/2017 8:11  2:11:00 PM               OK               OK   \n",
       "\n",
       "  Duration (hh:mm:ss)         DD-ES ES>=DD                DD-AS AS>=DD AF>DD  \\\n",
       "0          1:20:00 AM   0/1/00 9:00      D  2017-10-30T17:00:00      D     D   \n",
       "1          1:11:00 AM   0/1/00 9:00      D  2017-10-27T17:00:00      D     D   \n",
       "2          4:00:00 AM   0/1/00 9:00      D  2017-10-27T17:00:00      D     D   \n",
       "3          1:40:00 AM   0/1/00 9:00      D  2017-10-27T18:00:00      D     D   \n",
       "4          1:11:00 AM  0/1/00 12:00      D  1900-01-00T06:00:00      D     D   \n",
       "\n",
       "   Note  Unnamed: 36  Unnamed: 37  Unnamed: 38  Unnamed: 39  Unnamed: 40  \\\n",
       "0   NaN          NaN          NaN          NaN          NaN          NaN   \n",
       "1   NaN          NaN          NaN          NaN          NaN          NaN   \n",
       "2   NaN          NaN          NaN          NaN          NaN          NaN   \n",
       "3   NaN          NaN          NaN          NaN          NaN          NaN   \n",
       "4   NaN          NaN          NaN          NaN          NaN          NaN   \n",
       "\n",
       "   Unnamed: 41  Unnamed: 42  Unnamed: 43  Unnamed: 44  Unnamed: 45  \\\n",
       "0          NaN          NaN          NaN          NaN          NaN   \n",
       "1          NaN          NaN          NaN          NaN          NaN   \n",
       "2          NaN          NaN          NaN          NaN          NaN   \n",
       "3          NaN          NaN          NaN          NaN          NaN   \n",
       "4          NaN          NaN          NaN          NaN          NaN   \n",
       "\n",
       "   Unnamed: 46  Unnamed: 47  Unnamed: 48  Unnamed: 49  Unnamed: 50  \\\n",
       "0          NaN          NaN          NaN          NaN          NaN   \n",
       "1          NaN          NaN          NaN          NaN          NaN   \n",
       "2          NaN          NaN          NaN          NaN          NaN   \n",
       "3          NaN          NaN          NaN          NaN          NaN   \n",
       "4          NaN          NaN          NaN          NaN          NaN   \n",
       "\n",
       "   Unnamed: 51  Unnamed: 52  Unnamed: 53  Unnamed: 54  Unnamed: 55  \\\n",
       "0          NaN          NaN          NaN          NaN          NaN   \n",
       "1          NaN          NaN          NaN          NaN          NaN   \n",
       "2          NaN          NaN          NaN          NaN          NaN   \n",
       "3          NaN          NaN          NaN          NaN          NaN   \n",
       "4          NaN          NaN          NaN          NaN          NaN   \n",
       "\n",
       "   Unnamed: 56  Unnamed: 57  Unnamed: 58  Unnamed: 59  Unnamed: 60  \\\n",
       "0          NaN          NaN          NaN          NaN          NaN   \n",
       "1          NaN          NaN          NaN          NaN          NaN   \n",
       "2          NaN          NaN          NaN          NaN          NaN   \n",
       "3          NaN          NaN          NaN          NaN          NaN   \n",
       "4          NaN          NaN          NaN          NaN          NaN   \n",
       "\n",
       "   Unnamed: 61  Unnamed: 62  Unnamed: 63  \n",
       "0          NaN          NaN          NaN  \n",
       "1          NaN          NaN          NaN  \n",
       "2          NaN          NaN          NaN  \n",
       "3          NaN          NaN          NaN  \n",
       "4          NaN          NaN          NaN  "
      ]
     },
     "execution_count": 112,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import os \n",
    "\n",
    "pd.set_option('display.max_columns', None)\n",
    "pd.set_option('display.max_rows', None)\n",
    "\n",
    "taskFile = (r\"C:\\Users\\andrew.domenico\\OneDrive - Accenture\\Documents\\CTL\\Dispatch Optimization\\task.csv\")\n",
    "\n",
    "pwd = os.getcwd()\n",
    "os.chdir(os.path.dirname(taskFile))\n",
    "taskData = pd.read_csv(os.path.basename(taskFile))\n",
    "os.chdir(pwd)\n",
    "\n",
    "taskData.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 113,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   SerialNo  ExternalRefID  CallID    CTLDispatchCallID     CTLAggregationID  \\\n",
      "0         1         213116  213116    MRNV1099624001F00  M/JUNETEST01/171231   \n",
      "1         2         253122  253122    MRNV4542934002A00         H/1445077137   \n",
      "2         3         253130  253130    MRNV4542934001A00         R/1445077137   \n",
      "3         4          29319   29319  TINVC014723001PTD01                  NaN   \n",
      "4         5         296995  296995    MRNV4306921001A00         R/1446647892   \n",
      "\n",
      "   Number           EarlyStart     DueDate  Priority Area     Region  \\\n",
      "0       1  2017-10-30T08:00:00  2017-10-30         4   NV  Las Vegas   \n",
      "1       1  2017-10-27T08:00:00  2017-10-27         4   NV  Las Vegas   \n",
      "2       1  2017-10-27T08:00:00  2017-10-27         4   NV  Las Vegas   \n",
      "3       1  2017-10-27T09:00:00  2017-10-27         4   NV  Las Vegas   \n",
      "4       1  2017-10-29T07:00:00  2017-10-29         4   NV  Las Vegas   \n",
      "\n",
      "       District     Postcode        TaskType  Duration  \\\n",
      "0     East 2 NV  891156549.0   HSADSL2SANRIN      4800   \n",
      "1    North 2 NV  890311803.0   XXXXXXXXXXXIH      4260   \n",
      "2    North 2 NV  890311803.0   HSBNDA2FANRIN     14400   \n",
      "3    North 2 NV      89030.0  DSOCFEPREMDESX      6000   \n",
      "4  West West NV  891444443.0   XXXXXXXXXXXIH      4260   \n",
      "\n",
      "   NumberOfRequiredEngineers     AppointmentStart    AppointmentFinish  \\\n",
      "0                          1                  NaN                  NaN   \n",
      "1                          1                  NaN                  NaN   \n",
      "2                          1                  NaN                  NaN   \n",
      "3                          1                  NaN                  NaN   \n",
      "4                          1  2017-10-29T13:00:00  2017-10-29T17:00:00   \n",
      "\n",
      "    Latitude    Longitude  Street  City  State      CountryID  \\\n",
      "0  36.619675  -115.507186     NaN   NaN    NaN  UNITED STATES   \n",
      "1  36.627253  -115.516158     NaN   NaN    NaN  UNITED STATES   \n",
      "2  36.627253  -115.516158     NaN   NaN    NaN  UNITED STATES   \n",
      "3  36.619578  -115.511821     NaN   NaN    NaN  UNITED STATES   \n",
      "4  36.616566  -115.533112     NaN   NaN    NaN  UNITED STATES   \n",
      "\n",
      "   CTLDispatchReady       ES+duration AS+duration (AS+duration>=DD  \\\n",
      "0             False   10/30/2017 9:20  1:20:00 AM               OK   \n",
      "1              True   10/27/2017 9:11  1:11:00 AM               OK   \n",
      "2              True  10/27/2017 12:00  4:00:00 AM               OK   \n",
      "3              True  10/27/2017 10:40  1:40:00 AM               OK   \n",
      "4              True   10/29/2017 8:11  2:11:00 PM               OK   \n",
      "\n",
      "  (ES+duration>=DD Duration (hh:mm:ss)         DD-ES ES>=DD  \\\n",
      "0               OK          1:20:00 AM   0/1/00 9:00      D   \n",
      "1               OK          1:11:00 AM   0/1/00 9:00      D   \n",
      "2               OK          4:00:00 AM   0/1/00 9:00      D   \n",
      "3               OK          1:40:00 AM   0/1/00 9:00      D   \n",
      "4               OK          1:11:00 AM  0/1/00 12:00      D   \n",
      "\n",
      "                 DD-AS AS>=DD AF>DD  Note  Unnamed: 36  Unnamed: 37  \\\n",
      "0  2017-10-30T17:00:00      D     D   NaN          NaN          NaN   \n",
      "1  2017-10-27T17:00:00      D     D   NaN          NaN          NaN   \n",
      "2  2017-10-27T17:00:00      D     D   NaN          NaN          NaN   \n",
      "3  2017-10-27T18:00:00      D     D   NaN          NaN          NaN   \n",
      "4  1900-01-00T06:00:00      D     D   NaN          NaN          NaN   \n",
      "\n",
      "   Unnamed: 38  Unnamed: 39  Unnamed: 40  Unnamed: 41  Unnamed: 42  \\\n",
      "0          NaN          NaN          NaN          NaN          NaN   \n",
      "1          NaN          NaN          NaN          NaN          NaN   \n",
      "2          NaN          NaN          NaN          NaN          NaN   \n",
      "3          NaN          NaN          NaN          NaN          NaN   \n",
      "4          NaN          NaN          NaN          NaN          NaN   \n",
      "\n",
      "   Unnamed: 43  Unnamed: 44  Unnamed: 45  Unnamed: 46  Unnamed: 47  \\\n",
      "0          NaN          NaN          NaN          NaN          NaN   \n",
      "1          NaN          NaN          NaN          NaN          NaN   \n",
      "2          NaN          NaN          NaN          NaN          NaN   \n",
      "3          NaN          NaN          NaN          NaN          NaN   \n",
      "4          NaN          NaN          NaN          NaN          NaN   \n",
      "\n",
      "   Unnamed: 48  Unnamed: 49  Unnamed: 50  Unnamed: 51  Unnamed: 52  \\\n",
      "0          NaN          NaN          NaN          NaN          NaN   \n",
      "1          NaN          NaN          NaN          NaN          NaN   \n",
      "2          NaN          NaN          NaN          NaN          NaN   \n",
      "3          NaN          NaN          NaN          NaN          NaN   \n",
      "4          NaN          NaN          NaN          NaN          NaN   \n",
      "\n",
      "   Unnamed: 53  Unnamed: 54  Unnamed: 55 EarlyStartDate EarlyStartTime  \\\n",
      "0          NaN          NaN          NaN     2017-10-30       08:00:00   \n",
      "1          NaN          NaN          NaN     2017-10-27       08:00:00   \n",
      "2          NaN          NaN          NaN     2017-10-27       08:00:00   \n",
      "3          NaN          NaN          NaN     2017-10-27       09:00:00   \n",
      "4          NaN          NaN          NaN     2017-10-29       07:00:00   \n",
      "\n",
      "    DueTime AppointmentStartDate AppointmentStartTime AppointmentFinishDate  \\\n",
      "0  17:00:00                  NaN                  NaN                   NaN   \n",
      "1  17:00:00                  NaN                  NaN                   NaN   \n",
      "2  17:00:00                  NaN                  NaN                   NaN   \n",
      "3  18:00:00                  NaN                  NaN                   NaN   \n",
      "4  19:00:00           2017-10-29             13:00:00            2017-10-29   \n",
      "\n",
      "  AppointmentFinishTime  \n",
      "0                   NaN  \n",
      "1                   NaN  \n",
      "2                   NaN  \n",
      "3                   NaN  \n",
      "4              17:00:00  \n"
     ]
    }
   ],
   "source": [
    "#split the latitude and longitude strings keeping the final 6 numbers\n",
    "#insert a decimal point to the left of the final six numbers\n",
    "#concatenate the remaining numbers left of the decimal the decimal and the final 6\n",
    "\n",
    "#Convert Latitude and Longitude to strings\n",
    "taskData['Latitude'] = taskData['Latitude'].astype(str)\n",
    "taskData['Longitude'] = taskData['Longitude'].astype(str)\n",
    "\n",
    "#create new columns using string indexing\n",
    "taskData['last6Lat'] = taskData['Latitude'].str[-7:-1]\n",
    "taskData['last6Long'] = taskData['Longitude'].str[-7:-1]\n",
    "taskData['firstLat'] = taskData['Latitude'].str[:-6]\n",
    "taskData['firstLong'] = taskData['Longitude'].str[:-6]\n",
    "\n",
    "#Concat first and last lat and long with a decimal point between them\n",
    "taskData['Latitude'] = taskData.firstLat + \".\" + taskData.last6Lat\n",
    "taskData['Longitude'] = taskData.firstLong + \".\" + taskData.last6Long\n",
    "\n",
    "#split the dates and times into separate columns\n",
    "earlyDf = taskData['EarlyStart'].str.split(\"T\", n = 1, expand = True)\n",
    "taskData[\"EarlyStartDate\"] = earlyDf[0]\n",
    "taskData[\"EarlyStartTime\"] = earlyDf[1]\n",
    "\n",
    "dueDf = taskData['DueDate'].str.split(\"T\", n = 1, expand = True)\n",
    "taskData[\"DueDate\"] = dueDf[0]\n",
    "taskData[\"DueTime\"] = dueDf[1]\n",
    "\n",
    "aptStartDf = taskData['AppointmentStart'].str.split(\"T\", n = 1, expand = True)\n",
    "taskData[\"AppointmentStartDate\"] = aptStartDf[0]\n",
    "taskData[\"AppointmentStartTime\"] = aptStartDf[1]\n",
    "\n",
    "aptFinishDf = taskData['AppointmentFinish'].str.split(\"T\", n = 1, expand = True)\n",
    "taskData[\"AppointmentFinishDate\"] = aptFinishDf[0]\n",
    "taskData[\"AppointmentFinishTime\"] = aptFinishDf[1]\n",
    "\n",
    "#remove unused and temp columns\n",
    "taskData.drop(columns=[\"last6Lat\", \"last6Long\", \"firstLat\", \"firstLong\", \"Unnamed: 63\", \"Unnamed: 62\", \"Unnamed: 61\", \"Unnamed: 60\", \"Unnamed: 59\", \"Unnamed: 58\", \"Unnamed: 57\", \"Unnamed: 56\"], inplace = True)\n",
    "\n",
    "print(taskData.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
